variable "aws_region" {
  description = "AWS region the ETL Lambda and its S3 bucket live in."
  type        = string
  default     = "eu-west-2"
}

variable "project_name" {
  description = "Short name used as a prefix for resources that need one."
  type        = string
  default     = "space-weather"
}

variable "lambda_function_name" {
  description = "Name of the existing ETL Lambda function."
  type        = string
  default     = "space-weather-etl"
}

variable "lambda_exec_role_name" {
  description = "Name of the existing Lambda execution role (auto-generated by the Lambda console's 'create new role' flow, hence the random suffix and the /service-role/ path)."
  type        = string
  default     = "space-weather-etl-role-xvrt45ud"
}

variable "lambda_basic_execution_policy_name" {
  description = "Name of the existing customer-managed policy providing basic Lambda log permissions (auto-created alongside lambda_exec_role_name by the Lambda console, hence the random suffix)."
  type        = string
  default     = "AWSLambdaBasicExecutionRole-61671f01-2d08-448f-b0ba-a78120b02073"
}

variable "ecr_repository_name" {
  description = "Name of the existing ECR repository the Lambda image is pushed to."
  type        = string
  default     = "space-weather-etl"
}

variable "lambda_image_uri" {
  description = <<-EOT
    Image URI the aws_lambda_function is initially created with. deploy_lambda.yml
    overwrites the running image on every push to main via `update-function-code`,
    so Terraform must not fight that - see the lifecycle.ignore_changes block on
    the function resource. Only matters on first create/import.
  EOT
  type        = string
}

variable "lambda_memory_size" {
  description = "Lambda memory in MB - matches the live value (1028MB comfortably covers the ~536MB peak measured in docs/DECISIONS.md)."
  type        = number
  default     = 1028
}

variable "lambda_timeout" {
  description = "Lambda timeout in seconds. Normal ETL runs in ~8s; generous headroom for slow upstream fetches and the daily compaction run."
  type        = number
  default     = 300
}

variable "log_retention_days" {
  description = "CloudWatch Logs retention for the Lambda's log group."
  type        = number
  default     = 30
}

variable "s3_bucket_name" {
  description = "Name of the existing S3 bucket holding raw/transformed data and OVATION run-files."
  type        = string
  default     = "space-weather-raw"
}

variable "database_url" {
  description = "Supabase write connection string, injected as a Lambda env var."
  type        = string
  sensitive   = true
}

variable "fetch_sources" {
  description = <<-EOT
    Data sources with their own SuccessfulFetch CloudWatch metric and
    per-source silence alarm - one entry per key in LIVE_FETCHERS
    (src/extract/extract.py). put_fetch_metric(name) fires on every
    successful fetch regardless of how the fetcher is implemented, so this
    includes "ovation" even though it doesn't go through fetch_with_fallback
    (no FailedFetch on failure, but SuccessfulFetch on success same as the
    rest). ovation is prod-only in the pipeline itself, which matches this
    being a prod-only stack.
  EOT
  type        = list(string)
  default     = ["mag", "plasma", "dst", "kp", "ssn", "smoothed_ssn", "ovation"]
}

variable "main_schedule_expression" {
  description = "EventBridge schedule for the regular ETL run."
  type        = string
  default     = "rate(3 minutes)"
}

variable "compact_ovation_schedule_expression" {
  description = "EventBridge schedule for the once-daily OVATION compaction run."
  type        = string
  default     = "cron(0 0 * * ? *)"
}

variable "silence_alarm_period_seconds" {
  description = "Window the per-source silence alarm checks for zero SuccessfulFetch metrics. Matches the 'hasn't fetched fresh data in an hour' behaviour described in docs/DECISIONS.md."
  type        = number
  default     = 3600
}

variable "alert_email" {
  description = "Email address subscribed to the SNS alert topic. Leave blank to skip creating a subscription."
  type        = string
  default     = ""
}

variable "budget_name" {
  description = "Name of the existing AWS Budgets monthly cost budget."
  type        = string
  default     = "Monthly Cost Budget"
}

variable "monthly_budget_usd" {
  description = "AWS Budgets monthly cost threshold in USD."
  type        = string
  default     = "15"
}

variable "budget_alert_email" {
  description = "Email address notified by the AWS Budgets alert. Defaults to alert_email if left blank."
  type        = string
  default     = ""
}

variable "create_oidc_provider" {
  description = <<-EOT
    Whether to create the GitHub Actions OIDC provider (token.actions.githubusercontent.com).
    False by default - one already exists on this account (only one is allowed
    per issuer URL), referenced via existing_oidc_provider_arn instead.
  EOT
  type        = bool
  default     = false
}

variable "existing_oidc_provider_arn" {
  description = "ARN of the already-existing GitHub OIDC provider, used when create_oidc_provider is false."
  type        = string
  default     = "arn:aws:iam::494487213442:oidc-provider/token.actions.githubusercontent.com"
}

variable "github_org" {
  description = "GitHub org/user that owns this repo, used to scope the OIDC trust policy."
  type        = string
  default     = "Umair539"
}

variable "github_repo" {
  description = "GitHub repo name, used to scope the OIDC trust policy."
  type        = string
  default     = "Space_Weather_Dashboard"
}

variable "github_deploy_role_name" {
  description = "Name of the existing GitHub Actions OIDC deploy role used by deploy_lambda.yml."
  type        = string
  default     = "github-actions-deploy-etl"
}

variable "github_environment" {
  description = "GitHub Actions environment deploy_lambda.yml runs under - the OIDC trust condition is scoped to this (token sub claim is repo:<org>/<repo>:environment:<this>), matching the job's `environment: prod` setting rather than a branch ref."
  type        = string
  default     = "prod"
}

# --- EventBridge invocation roles ---
# The console created one IAM role per rule to invoke the Lambda (rather than
# a Lambda resource-policy grant) when these were set up by hand. Referenced
# here, not owned by this config, so importing the targets doesn't produce a
# permanent diff trying to null out role_arn.

variable "etl_schedule_event_role_arn" {
  description = "IAM role EventBridge assumes to invoke the Lambda for the main ETL schedule."
  type        = string
  default     = "arn:aws:iam::494487213442:role/service-role/Amazon_EventBridge_Invoke_Lambda_215459010"
}

variable "compact_ovation_event_role_arn" {
  description = "IAM role EventBridge assumes to invoke the Lambda for the daily OVATION compaction schedule."
  type        = string
  default     = "arn:aws:iam::494487213442:role/service-role/Amazon_EventBridge_Invoke_Lambda_1572976812"
}

# --- Cloudflare R2 ---

variable "cloudflare_api_token" {
  description = "Cloudflare API token with R2 edit permission on the account."
  type        = string
  sensitive   = true
}

variable "cloudflare_account_id" {
  description = "Cloudflare account ID that owns the R2 buckets (also embedded in R2_ENDPOINT)."
  type        = string
  default     = "67e2c43a7c62257588605b51541a1caa"
}

variable "r2_bucket_name" {
  description = "Name of the prod R2 bucket that holds compacted OVATION output (the copy meant for repeated external reads / free egress)."
  type        = string
  default     = "space-weather-prod"
}

variable "r2_location" {
  description = "Optional R2 jurisdiction/location hint (e.g. \"WEUR\", \"ENAM\"). Leave blank to let Cloudflare choose automatically."
  type        = string
  default     = ""
}

variable "r2_access_key_id" {
  description = "R2 (S3-compatible) access key ID, injected as a Lambda env var so the ETL can write compacted OVATION output. Generated separately in the Cloudflare dashboard (R2 API tokens aren't a Terraform-managed resource)."
  type        = string
  sensitive   = true
}

variable "r2_secret_access_key" {
  description = "R2 (S3-compatible) secret access key, injected as a Lambda env var."
  type        = string
  sensitive   = true
}
